name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: make
      working-directory: Code
    - name: make check
      run: make check
      working-directory: Code
    - name: make distcheck
      run: make distcheck
      working-directory: Code
